name: socialx
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  flag: ^6.0.0
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.3
  http: ^0.13.5
  provider: ^5.0.0
  flutter_secure_storage: ^3.3.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
